package org.tlsys.css

//import kotlin.js.definedExternally

//
external interface CssDeclaration {
    var text: String?
        get() = definedExternally
        set(value) = definedExternally
    val length: Int?
        get() = definedExternally
    var float: String?
        get() = definedExternally
        set(value) = definedExternally
    var _dashed_attribute: String?
        get() = definedExternally
        set(value) = definedExternally
    var _camel_cased_attribute: String?
        get() = definedExternally
        set(value) = definedExternally
    var alignContent: String?
        get() = definedExternally
        set(value) = definedExternally
    var alignItems: String?
        get() = definedExternally
        set(value) = definedExternally
    var alignSelf: String?
        get() = definedExternally
        set(value) = definedExternally
    var animation: String?
        get() = definedExternally
        set(value) = definedExternally
    var animationDelay: String?
        get() = definedExternally
        set(value) = definedExternally
    var animationDirection: String?
        get() = definedExternally
        set(value) = definedExternally
    var animationDuration: String?
        get() = definedExternally
        set(value) = definedExternally
    var animationFillMode: String?
        get() = definedExternally
        set(value) = definedExternally
    var animationIterationCount: String?
        get() = definedExternally
        set(value) = definedExternally
    var animationName: String?
        get() = definedExternally
        set(value) = definedExternally
    var animationPlayState: String?
        get() = definedExternally
        set(value) = definedExternally
    var animationTimingFunction: String?
        get() = definedExternally
        set(value) = definedExternally
    var backfaceVisibility: String?
        get() = definedExternally
        set(value) = definedExternally
    var background: String?
        get() = definedExternally
        set(value) = definedExternally
    var backgroundAttachment: String?
        get() = definedExternally
        set(value) = definedExternally
    var backgroundClip: String?
        get() = definedExternally
        set(value) = definedExternally
    var backgroundColor: String?
        get() = definedExternally
        set(value) = definedExternally
    var backgroundImage: String?
        get() = definedExternally
        set(value) = definedExternally
    var backgroundOrigin: String?
        get() = definedExternally
        set(value) = definedExternally
    var backgroundPosition: String?
        get() = definedExternally
        set(value) = definedExternally
    var backgroundRepeat: String?
        get() = definedExternally
        set(value) = definedExternally
    var backgroundSize: String?
        get() = definedExternally
        set(value) = definedExternally
    var border: String?
        get() = definedExternally
        set(value) = definedExternally
    var borderBottom: String?
        get() = definedExternally
        set(value) = definedExternally
    var borderBottomColor: String?
        get() = definedExternally
        set(value) = definedExternally
    var borderBottomLeftRadius: String?
        get() = definedExternally
        set(value) = definedExternally
    var borderBottomRightRadius: String?
        get() = definedExternally
        set(value) = definedExternally
    var borderBottomStyle: String?
        get() = definedExternally
        set(value) = definedExternally
    var borderBottomWidth: String?
        get() = definedExternally
        set(value) = definedExternally
    var borderCollapse: String?
        get() = definedExternally
        set(value) = definedExternally
    var borderColor: String?
        get() = definedExternally
        set(value) = definedExternally
    var borderImage: String?
        get() = definedExternally
        set(value) = definedExternally
    var borderImageOutset: String?
        get() = definedExternally
        set(value) = definedExternally
    var borderImageRepeat: String?
        get() = definedExternally
        set(value) = definedExternally
    var borderImageSlice: String?
        get() = definedExternally
        set(value) = definedExternally
    var borderImageSource: String?
        get() = definedExternally
        set(value) = definedExternally
    var borderImageWidth: String?
        get() = definedExternally
        set(value) = definedExternally
    var borderLeft: String?
        get() = definedExternally
        set(value) = definedExternally
    var borderLeftColor: String?
        get() = definedExternally
        set(value) = definedExternally
    var borderLeftStyle: String?
        get() = definedExternally
        set(value) = definedExternally
    var borderLeftWidth: String?
        get() = definedExternally
        set(value) = definedExternally
    var borderRadius: String?
        get() = definedExternally
        set(value) = definedExternally
    var borderRight: String?
        get() = definedExternally
        set(value) = definedExternally
    var borderRightColor: String?
        get() = definedExternally
        set(value) = definedExternally
    var borderRightStyle: String?
        get() = definedExternally
        set(value) = definedExternally
    var borderRightWidth: String?
        get() = definedExternally
        set(value) = definedExternally
    var borderSpacing: String?
        get() = definedExternally
        set(value) = definedExternally
    var borderStyle: String?
        get() = definedExternally
        set(value) = definedExternally
    var borderTop: String?
        get() = definedExternally
        set(value) = definedExternally
    var borderTopColor: String?
        get() = definedExternally
        set(value) = definedExternally
    var borderTopLeftRadius: String?
        get() = definedExternally
        set(value) = definedExternally
    var borderTopRightRadius: String?
        get() = definedExternally
        set(value) = definedExternally
    var borderTopStyle: String?
        get() = definedExternally
        set(value) = definedExternally
    var borderTopWidth: String?
        get() = definedExternally
        set(value) = definedExternally
    var borderWidth: String?
        get() = definedExternally
        set(value) = definedExternally
    var bottom: String?
        get() = definedExternally
        set(value) = definedExternally
    var boxDecorationBreak: String?
        get() = definedExternally
        set(value) = definedExternally
    var boxShadow: String?
        get() = definedExternally
        set(value) = definedExternally
    var boxSizing: String?
        get() = definedExternally
        set(value) = definedExternally
    var breakAfter: String?
        get() = definedExternally
        set(value) = definedExternally
    var breakBefore: String?
        get() = definedExternally
        set(value) = definedExternally
    var breakInside: String?
        get() = definedExternally
        set(value) = definedExternally
    var captionSide: String?
        get() = definedExternally
        set(value) = definedExternally
    var clear: String?
        get() = definedExternally
        set(value) = definedExternally
    var clip: String?
        get() = definedExternally
        set(value) = definedExternally
    var color: String?
        get() = definedExternally
        set(value) = definedExternally
    var columnCount: String?
        get() = definedExternally
        set(value) = definedExternally
    var columnFill: String?
        get() = definedExternally
        set(value) = definedExternally
    var columnGap: String?
        get() = definedExternally
        set(value) = definedExternally
    var columnRule: String?
        get() = definedExternally
        set(value) = definedExternally
    var columnRuleColor: String?
        get() = definedExternally
        set(value) = definedExternally
    var columnRuleStyle: String?
        get() = definedExternally
        set(value) = definedExternally
    var columnRuleWidth: String?
        get() = definedExternally
        set(value) = definedExternally
    var columnSpan: String?
        get() = definedExternally
        set(value) = definedExternally
    var columnWidth: String?
        get() = definedExternally
        set(value) = definedExternally
    var columns: String?
        get() = definedExternally
        set(value) = definedExternally
    var content: String?
        get() = definedExternally
        set(value) = definedExternally
    var counterIncrement: String?
        get() = definedExternally
        set(value) = definedExternally
    var counterReset: String?
        get() = definedExternally
        set(value) = definedExternally
    var cursor: String?
        get() = definedExternally
        set(value) = definedExternally
    var direction: String?
        get() = definedExternally
        set(value) = definedExternally
    var display: String?
        get() = definedExternally
        set(value) = definedExternally
    var emptyCells: String?
        get() = definedExternally
        set(value) = definedExternally
    var filter: String?
        get() = definedExternally
        set(value) = definedExternally
    var flex: String?
        get() = definedExternally
        set(value) = definedExternally
    var flexBasis: String?
        get() = definedExternally
        set(value) = definedExternally
    var flexDirection: String?
        get() = definedExternally
        set(value) = definedExternally
    var flexFlow: String?
        get() = definedExternally
        set(value) = definedExternally
    var flexGrow: String?
        get() = definedExternally
        set(value) = definedExternally
    var flexShrink: String?
        get() = definedExternally
        set(value) = definedExternally
    var flexWrap: String?
        get() = definedExternally
        set(value) = definedExternally
    var font: String?
        get() = definedExternally
        set(value) = definedExternally
    var fontFamily: String?
        get() = definedExternally
        set(value) = definedExternally
    var fontFeatureSettings: String?
        get() = definedExternally
        set(value) = definedExternally
    var fontKerning: String?
        get() = definedExternally
        set(value) = definedExternally
    var fontLanguageOverride: String?
        get() = definedExternally
        set(value) = definedExternally
    var fontSize: String?
        get() = definedExternally
        set(value) = definedExternally
    var fontSizeAdjust: String?
        get() = definedExternally
        set(value) = definedExternally
    var fontStretch: String?
        get() = definedExternally
        set(value) = definedExternally
    var fontStyle: String?
        get() = definedExternally
        set(value) = definedExternally
    var fontSynthesis: String?
        get() = definedExternally
        set(value) = definedExternally
    var fontVariant: String?
        get() = definedExternally
        set(value) = definedExternally
    var fontVariantAlternates: String?
        get() = definedExternally
        set(value) = definedExternally
    var fontVariantCaps: String?
        get() = definedExternally
        set(value) = definedExternally
    var fontVariantEastAsian: String?
        get() = definedExternally
        set(value) = definedExternally
    var fontVariantLigatures: String?
        get() = definedExternally
        set(value) = definedExternally
    var fontVariantNumeric: String?
        get() = definedExternally
        set(value) = definedExternally
    var fontVariantPosition: String?
        get() = definedExternally
        set(value) = definedExternally
    var fontWeight: String?
        get() = definedExternally
        set(value) = definedExternally
    var hangingPunctuation: String?
        get() = definedExternally
        set(value) = definedExternally
    var height: String?
        get() = definedExternally
        set(value) = definedExternally
    var hyphens: String?
        get() = definedExternally
        set(value) = definedExternally
    var imageOrientation: String?
        get() = definedExternally
        set(value) = definedExternally
    var imageRendering: String?
        get() = definedExternally
        set(value) = definedExternally
    var imageResolution: String?
        get() = definedExternally
        set(value) = definedExternally
    var imeMode: String?
        get() = definedExternally
        set(value) = definedExternally
    var justifyContent: String?
        get() = definedExternally
        set(value) = definedExternally
    var left: String?
        get() = definedExternally
        set(value) = definedExternally
    var letterSpacing: String?
        get() = definedExternally
        set(value) = definedExternally
    var lineBreak: String?
        get() = definedExternally
        set(value) = definedExternally
    var lineHeight: String?
        get() = definedExternally
        set(value) = definedExternally
    var listStyle: String?
        get() = definedExternally
        set(value) = definedExternally
    var listStyleImage: String?
        get() = definedExternally
        set(value) = definedExternally
    var listStylePosition: String?
        get() = definedExternally
        set(value) = definedExternally
    var listStyleType: String?
        get() = definedExternally
        set(value) = definedExternally
    var margin: String?
        get() = definedExternally
        set(value) = definedExternally
    var marginBottom: String?
        get() = definedExternally
        set(value) = definedExternally
    var marginLeft: String?
        get() = definedExternally
        set(value) = definedExternally
    var marginRight: String?
        get() = definedExternally
        set(value) = definedExternally
    var marginTop: String?
        get() = definedExternally
        set(value) = definedExternally
    var mark: String?
        get() = definedExternally
        set(value) = definedExternally
    var markAfter: String?
        get() = definedExternally
        set(value) = definedExternally
    var markBefore: String?
        get() = definedExternally
        set(value) = definedExternally
    var marks: String?
        get() = definedExternally
        set(value) = definedExternally
    var marqueeDirection: String?
        get() = definedExternally
        set(value) = definedExternally
    var marqueePlayCount: String?
        get() = definedExternally
        set(value) = definedExternally
    var marqueeSpeed: String?
        get() = definedExternally
        set(value) = definedExternally
    var marqueeStyle: String?
        get() = definedExternally
        set(value) = definedExternally
    var mask: String?
        get() = definedExternally
        set(value) = definedExternally
    var maskType: String?
        get() = definedExternally
        set(value) = definedExternally
    var maxHeight: String?
        get() = definedExternally
        set(value) = definedExternally
    var maxWidth: String?
        get() = definedExternally
        set(value) = definedExternally
    var minHeight: String?
        get() = definedExternally
        set(value) = definedExternally
    var minWidth: String?
        get() = definedExternally
        set(value) = definedExternally
    var navDown: String?
        get() = definedExternally
        set(value) = definedExternally
    var navIndex: String?
        get() = definedExternally
        set(value) = definedExternally
    var navLeft: String?
        get() = definedExternally
        set(value) = definedExternally
    var navRight: String?
        get() = definedExternally
        set(value) = definedExternally
    var navUp: String?
        get() = definedExternally
        set(value) = definedExternally
    var objectFit: String?
        get() = definedExternally
        set(value) = definedExternally
    var objectPosition: String?
        get() = definedExternally
        set(value) = definedExternally
    var opacity: Double?
        get() = definedExternally
        set(value) = definedExternally
    var order: String?
        get() = definedExternally
        set(value) = definedExternally
    var orphans: String?
        get() = definedExternally
        set(value) = definedExternally
    var outline: String?
        get() = definedExternally
        set(value) = definedExternally
    var outlineColor: String?
        get() = definedExternally
        set(value) = definedExternally
    var outlineOffset: String?
        get() = definedExternally
        set(value) = definedExternally
    var outlineStyle: String?
        get() = definedExternally
        set(value) = definedExternally
    var outlineWidth: String?
        get() = definedExternally
        set(value) = definedExternally
    var overflowWrap: String?
        get() = definedExternally
        set(value) = definedExternally
    var overflow: String?
        get() = definedExternally
        set(value) = definedExternally
    var overflowX: String?
        get() = definedExternally
        set(value) = definedExternally
    var overflowY: String?
        get() = definedExternally
        set(value) = definedExternally
    var padding: String?
        get() = definedExternally
        set(value) = definedExternally
    var paddingBottom: String?
        get() = definedExternally
        set(value) = definedExternally
    var paddingLeft: String?
        get() = definedExternally
        set(value) = definedExternally
    var paddingRight: String?
        get() = definedExternally
        set(value) = definedExternally
    var paddingTop: String?
        get() = definedExternally
        set(value) = definedExternally
    var pageBreakAfter: String?
        get() = definedExternally
        set(value) = definedExternally
    var pageBreakBefore: String?
        get() = definedExternally
        set(value) = definedExternally
    var pageBreakInside: String?
        get() = definedExternally
        set(value) = definedExternally
    var perspective: String?
        get() = definedExternally
        set(value) = definedExternally
    var perspectiveOrigin: String?
        get() = definedExternally
        set(value) = definedExternally
    var phonemes: String?
        get() = definedExternally
        set(value) = definedExternally
    var position: String?
        get() = definedExternally
        set(value) = definedExternally
    var quotes: String?
        get() = definedExternally
        set(value) = definedExternally
    var resize: String?
        get() = definedExternally
        set(value) = definedExternally
    var rest: String?
        get() = definedExternally
        set(value) = definedExternally
    var restAfter: String?
        get() = definedExternally
        set(value) = definedExternally
    var restBefore: String?
        get() = definedExternally
        set(value) = definedExternally
    var right: String?
        get() = definedExternally
        set(value) = definedExternally
    var tabSize: String?
        get() = definedExternally
        set(value) = definedExternally
    var tableLayout: String?
        get() = definedExternally
        set(value) = definedExternally
    var textAlign: String?
        get() = definedExternally
        set(value) = definedExternally
    var textAlignLast: String?
        get() = definedExternally
        set(value) = definedExternally
    var textCombineUpright: String?
        get() = definedExternally
        set(value) = definedExternally
    var textDecoration: String?
        get() = definedExternally
        set(value) = definedExternally
    var textDecorationColor: String?
        get() = definedExternally
        set(value) = definedExternally
    var textDecorationLine: String?
        get() = definedExternally
        set(value) = definedExternally
    var textDecorationStyle: String?
        get() = definedExternally
        set(value) = definedExternally
    var textIndent: String?
        get() = definedExternally
        set(value) = definedExternally
    var textJustify: String?
        get() = definedExternally
        set(value) = definedExternally
    var textOrientation: String?
        get() = definedExternally
        set(value) = definedExternally
    var textOverflow: String?
        get() = definedExternally
        set(value) = definedExternally
    var textShadow: String?
        get() = definedExternally
        set(value) = definedExternally
    var textTransform: String?
        get() = definedExternally
        set(value) = definedExternally
    var textUnderlinePosition: String?
        get() = definedExternally
        set(value) = definedExternally
    var top: String?
        get() = definedExternally
        set(value) = definedExternally
    var transform: String?
        get() = definedExternally
        set(value) = definedExternally
    var transformOrigin: String?
        get() = definedExternally
        set(value) = definedExternally
    var transformStyle: String?
        get() = definedExternally
        set(value) = definedExternally
    var transition: String?
        get() = definedExternally
        set(value) = definedExternally
    var transitionDelay: String?
        get() = definedExternally
        set(value) = definedExternally
    var transitionDuration: String?
        get() = definedExternally
        set(value) = definedExternally
    var transitionProperty: String?
        get() = definedExternally
        set(value) = definedExternally
    var transitionTimingFunction: String?
        get() = definedExternally
        set(value) = definedExternally
    var unicodeBidi: String?
        get() = definedExternally
        set(value) = definedExternally
    var verticalAlign: String?
        get() = definedExternally
        set(value) = definedExternally
    var visibility: String?
        get() = definedExternally
        set(value) = definedExternally
    var voiceBalance: String?
        get() = definedExternally
        set(value) = definedExternally
    var voiceDuration: String?
        get() = definedExternally
        set(value) = definedExternally
    var voicePitch: String?
        get() = definedExternally
        set(value) = definedExternally
    var voicePitchRange: String?
        get() = definedExternally
        set(value) = definedExternally
    var voiceRate: String?
        get() = definedExternally
        set(value) = definedExternally
    var voiceStress: String?
        get() = definedExternally
        set(value) = definedExternally
    var voiceVolume: String?
        get() = definedExternally
        set(value) = definedExternally
    var whiteSpace: String?
        get() = definedExternally
        set(value) = definedExternally
    var widows: String?
        get() = definedExternally
        set(value) = definedExternally
    var width: String?
        get() = definedExternally
        set(value) = definedExternally
    var wordBreak: String?
        get() = definedExternally
        set(value) = definedExternally
    var wordSpacing: String?
        get() = definedExternally
        set(value) = definedExternally
    var wordWrap: String?
        get() = definedExternally
        set(value) = definedExternally
    var writingMode: String?
        get() = definedExternally
        set(value) = definedExternally
    var zIndex: Int?
        get() = definedExternally
        set(value) = definedExternally
    var fill: String?
        get() = definedExternally
        set(value) = definedExternally
    var stroke: String?
        get() = definedExternally
        set(value) = definedExternally
    var strokeWidth: String?
        get() = definedExternally
        set(value) = definedExternally
    var stopColor: String?
        get() = definedExternally
        set(value) = definedExternally
    var clipPath: String?
        get() = definedExternally
        set(value) = definedExternally

}